### ISSUE TITLE
Структура папки проекта (дизайнер) 

### ISSUE THREAD

**Issue by vovs03** [OsArts/stack#124]
# :dart: Старт нового проекта

![папка дизайнера](https://habrastorage.org/r/w1560/files/afc/5a3/a70/afc5a3a706fa4df2835d6b3b581c31cd.png)

## «01_incoming»

В папке «Входящие» храню полученные от клиента материалы: Техническое задание, брифы, брендбук, фотографии, тексты и пр.

## «02_inspiration»

В папке «Вдохновение» складываю все материалы, которые помогут в работе. Сайты конкурентов, интересные дизайн-решения, цветовые палитры, мудборды, интересные фотографии из фотобанков (в виде превьюшек).

## «03_development»

```yaml
---

Work:
  - 01_current:
    - NameProject:
       01_incoming
       02_inspiration
       03_development
         - _archive  : "Хранение версий файлов"
         - _fonts    : "Шрифты"
         - img       : "Изображения из внешних источников"
         - html      : "Код"
         - vector    : "Созданные изображения(вектор) + логотипы, иконки"
         - pdf       : "Превью, или готовые документы-листы"
      04_final
  - 02_support:
  - 03_final:
```

Основная рабочая папка — «Разработка». Её структура зависит от размера проекта. Если проект небольшой, то файлы хранятся в ней без дополнительной группировки.

> image

В больших проектах внутри «03_development» создаются подпапки, такие как «img» — для фотографий, картинок иллюстраций, «vector» — для векторных иллюстраций, логотипов, иконок, «wireframes» — для прототипов сайта. Рабочие файлы размещены в корневой директории.

Классная фича macOs — отображение колонками с сортировкой по программе. Навигация становится быстрой и наглядной.

> image

Так же, создаю в «03_development» папку со шрифтами «_fonts», и папку «_archive» для хранения версий файлов.

Если в файле планируется вносить большое количество изменений, то создаю его дубликат, а старую версию переношу в папку «_archive».

:warning: **Все файлы называю согласно правилу:**
```md
- Номер (например, номер раздела в структуре сайта)
  - Используется не всегда, а только если нужна сортировка);
- Название;
- Версия.
```
Файл, который называется `03_services_04.psd`, сообщает слева-направо, что это третий раздел сайта, который называется «Услуги», и перед нами 4-я версия файла. Если мы откроем папку «archive», то найдём там `03_services_01.psd`, `03_services_02.psd`, «03_services_03.psd» которые хранят предыдущие итерации раздела.

С использованием Sketch и артбордов стало проще, файл называется по имени проекта, например «pinhost_04.sketch» (четвёртая версия сайта PinHost).

## «04_final»

> image

Папка «Финал» хранит последние версии файлов, которые будут передаваться заказчику. Здесь не должно быть файлов со старыми версиями проекта, только актуальные данные. Название файла, отправленного в эту директорию, не должно содержать номер версии. Например, файл который назывался «03_services_04.psd» после завершения работ и дублирования в папке «Final» должен носить название «03_services.psd».

Получается, последние версии файла хранятся в двух папках — «03_development» и «04_final», но с различными названиями, благодаря чему, вероятность утери файла стремиться к нулю.

- https://m.habr.com/ru/post/319296/
